### ISSUE TITLE
Set level of all namespaces at once

### ISSUE THREAD

**Issue by kamilash** [NeowayLabs/logger#2]
It would be nice to be able to change the log level of all namespaces in only one request.

The JSON could be the same that the api return on GET, something like:

curl -XPUT http://localhost:8080/logger/ --data '{"_default_":"debug","namespace1":"debug","namespace2":"debug","namespace3":"debug"}'

and

curl -XPUT http://localhost:8080/logger/ --data '{"all":"debug"}'

**Comment by katcipis** [comment]
Makes sense for me
